push:
    branches: [main, develop]
pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8","3.10"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{matrix.python-version}}
              uses:
                with:
                    python-version: ${{matrix.python-version}}
            - name: Install pytest
              run: python -m pip install pytest
            - name: Test with pytest
              run : pytest